version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nikka-backend
    # network_mode "host" hace que el contenedor comparta la red real del VPS.
    # Ya no hace falta mapear puertos (ports: - "8081:8081") porque tomará el 8081 nativo.
    network_mode: "host"
    environment:
      # Ahora puede conectarse a localhost tal como si estuviera instalado en el VPS nativamente
      - SPRING_DATASOURCE_URL=jdbc:mariadb://127.0.0.1:3306/nikka_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Tangoleyro007
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://app2.casa-glass.com/api
    container_name: nikka-frontend
    ports:
      - "3002:3002"
    restart: always
