version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nikka-backend
    ports:
      - "8081:8081"
    environment:
      # Conexión directa a través de la IP del VPS como especifica tu manual
      - SPRING_DATASOURCE_URL=jdbc:mariadb://148.230.87.167:3306/nikka_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Tangoleyro007
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://app2.casa-glass.com/api
    container_name: nikka-frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
    restart: always
