version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nikka-backend
    ports:
      - "8081:8081"
    environment:
      # Conectamos usando el nombre interno del contenedor de tu VPS
      - SPRING_DATASOURCE_URL=jdbc:mariadb://compose-mariadb-1:3306/nikka_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Tangoleyro007
    networks:
      - default
      - casa_glass_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://app2.casa-glass.com/api
    container_name: nikka-frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
    restart: always

networks:
  casa_glass_network:
    external: true
    name: compose_default
